# Generated by Django 3.2.7 on 2021-10-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='GithubLink',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='InstaLink',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='TwitterLink',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='facebookLink',
            field=models.URLField(blank=True),
        ),
    ]
