# Generated by Django 3.2.7 on 2021-10-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='image',
            field=models.ImageField(default='default.png', upload_to='icons'),
        ),
    ]
