# Generated by Django 3.2.7 on 2021-10-10 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='options',
            field=models.CharField(choices=[('FIRST SEMESTER', 'First'), ('SECOND SEMESTER', 'Second'), ('THIRD SEMESTER', 'Third'), ('FOURTH SEMESTER', 'Fourth'), ('FIFTH SEMESTER', 'Fifth'), ('SIXTH SEMESTER', 'Sixth'), ('SEVENTH SEMESTER', 'Seventh'), ('EIGHT SEMESTER', 'Eight')], default='FIRST SEMESTER', max_length=80),
        ),
    ]
