# Generated by Django 3.2.7 on 2021-10-28 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='blog.semester'),
        ),
    ]
