# Generated by Django 3.2.7 on 2021-11-01 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_subjects_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, upload_to='adminuploads/')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='blog.subjects')),
            ],
        ),
    ]
