# Generated by Django 3.2.7 on 2021-11-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_notefiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
