# Generated by Django 3.2.7 on 2021-11-02 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_subjects_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='semester',
        ),
        migrations.DeleteModel(
            name='NoteFiles',
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
    ]
