# Generated by Django 3.2.7 on 2021-11-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20211102_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='files',
            field=models.FileField(upload_to='files/'),
        ),
    ]
