# Generated by Django 2.1 on 2022-03-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_blog_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='like',
            field=models.DecimalField(blank=True, decimal_places=100, default='0', max_digits=1000, null=True),
        ),
    ]
