# Generated by Django 2.1 on 2022-03-30 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_blog_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='like',
        ),
    ]
