# Generated by Django 2.1 on 2022-03-31 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_blog_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='likes',
        ),
    ]
