# Generated by Django 3.2.7 on 2021-11-02 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('content', models.TextField()),
                ('image', models.ImageField(default='default.png', upload_to='icons')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('code', models.TextField()),
                ('options', models.CharField(choices=[('FIRST SEMESTER', 'First'), ('SECOND SEMESTER', 'Second'), ('THIRD SEMESTER', 'Third'), ('FOURTH SEMESTER', 'Fourth'), ('FIFTH SEMESTER', 'Fifth'), ('SIXTH SEMESTER', 'Sixth'), ('SEVENTH SEMESTER', 'Seventh'), ('EIGHT SEMESTER', 'Eight')], default='FIRST SEMESTER', max_length=80)),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='csit.semester')),
            ],
        ),
        migrations.CreateModel(
            name='NoteFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, upload_to='adminuploads/')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='csit.subject')),
            ],
        ),
    ]
