# Generated by Django 3.2.7 on 2021-11-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
