# Generated by Django 3.2.7 on 2021-11-16 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csit', '0004_notefile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notefile',
            name='slug',
        ),
    ]
