# Generated by Django 3.2.7 on 2021-11-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csit', '0006_auto_20211116_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='notefile',
            name='if_not_present',
            field=models.CharField(default='is not upload yet.', max_length=50),
        ),
    ]
