# Generated by Django 3.2.7 on 2021-11-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csit', '0007_notefile_if_not_present'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='options',
        ),
        migrations.AddField(
            model_name='semester',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=80),
        ),
        migrations.AddField(
            model_name='subject',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=80),
        ),
    ]
