# Generated by Django 3.2.7 on 2021-11-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csit', '0008_auto_20211123_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='fullMarks',
            field=models.CharField(default='60', max_length=90),
        ),
        migrations.AddField(
            model_name='subject',
            name='labMarks',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
