# Generated by Django 2.1 on 2022-03-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csit', '0010_auto_20220204_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
