# Generated by Django 2.1 on 2022-03-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csit', '0011_subject_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='link',
        ),
        migrations.AddField(
            model_name='notefile',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
