# Generated by Django 3.2 on 2022-05-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csit', '0013_auto_20220512_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notefile',
            name='files',
        ),
        migrations.RemoveField(
            model_name='notefile',
            name='if_not_present',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='image',
        ),
        migrations.AlterField(
            model_name='subject',
            name='labMarks',
            field=models.CharField(blank=True, default='25', max_length=90, null=True),
        ),
    ]
