# Generated by Django 3.2 on 2022-06-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csit', '0014_auto_20220512_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
