# Generated by Django 3.2 on 2022-06-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csit', '0015_semester_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='notefile',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
