# Generated by Django 3.2 on 2022-06-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csit', '0016_notefile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='notefile',
            name='subject_name',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
