# Generated by Django 3.2 on 2022-07-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csit', '0017_notefile_subject_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notefile',
            name='subject_name',
        ),
        migrations.AddField(
            model_name='notefile',
            name='download_link',
            field=models.URLField(null=True),
        ),
    ]
